---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: wordpress2
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress2
        tier: frontend
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name:  WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: user3
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_DB_NAME
          value: wpdb3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m 
         
