---
apiVersion: v1
kind: Service
metadata:
 name: wordpress
 labels:
   app: wordpress
spec:
 type: LoadBalancer
 ports:
   - port: 80
     protocol: TCP
     targetPort: 80
 selector:
   app: wordpress
   tier: frontend
---
apiVersion: v1
kind: Service
metadata:
 name: wordpress2
 labels:
   app: wordpress2
spec:
 type: LoadBalancer
 ports:
   - port: 80
     protocol: TCP
     targetPort: 80
 selector:
   app: wordpress2
   tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql   # will be used as a value in

  labels:                 # WORDPRESS_DB_HOST in wordpress-deploy.yml
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    #app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /wordpress
        backend:
          serviceName: wordpress
          servicePort: 80
      - path: /wordpress2
        backend:
          serviceName: wordpress2
          servicePort: 80
      